rebuild

diff --git a/perlbrew b/perlbrew
--- a/perlbrew
+++ b/perlbrew
@@ -30,8 +30,15 @@ $fatpacked{"App/perlbrew.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'AP
       @INC = @oldinc;
   }
   
-  use List::Util qw/min/;
   use Getopt::Long ();
+  
+  sub min(@) {
+      my $m = $_[0];
+      for(@_) {
+          $m = $_ if $_ < $m;
+      }
+      return $m;
+  }
   
   sub uniq {
       my %seen; grep { !$seen{$_}++ } @_;
@@ -804,7 +811,7 @@ $fatpacked{"App/perlbrew.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'AP
       my $pb_home_dir = $self->path_with_tilde($PERLBREW_HOME);
   
       my $code = qq(    source $root_dir/etc/${shrc});
-      if ($PERLBREW_HOME ne joinpath($ENV{HOME}, ".perlbrew")) {
+      if ($PERLBREW_HOME ne joinpath($self->env('HOME'), ".perlbrew")) {
           $code = "    export PERLBREW_HOME=$pb_home_dir\n" . $code;
       }
   
@@ -1407,6 +1414,15 @@ $fatpacked{"App/perlbrew.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'AP
                   or die "Could not open '$sitecustomize' for reading: $!\n";
               print {$dst} do { local $/; <$src> };
           }
+  
+          my $version_file =
+            joinpath( $self->root, 'perls', $installation_name, '.version' );
+  
+          if ( -e $version_file ) {
+              unlink($version_file)
+                or die "Could not unlink $version_file file: $!\n";
+          }
+  
           print "$installation_name is successfully installed.\n";
       }
       else {
@@ -1434,7 +1450,7 @@ $fatpacked{"App/perlbrew.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'AP
       my $body = http_get($url) or die "\nERROR: Failed to retrieve $program_name executable.\n\n";
   
       unless ($body =~ m{\A#!/}s) {
-          my $x = joinpath($ENV{TMPDIR} || "/tmp", "${program_name}.downloaded.$$");
+          my $x = joinpath($self->env('TMPDIR') || "/tmp", "${program_name}.downloaded.$$");
           my $message = "\nERROR: The downloaded $program_name program seem to be invalid. Please check if the following URL can be reached correctly\n\n\t$url\n\n...and try again latter.";
   
           unless (-f $x) {
@@ -1521,7 +1537,7 @@ $fatpacked{"App/perlbrew.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'AP
               name        => $name,
               orig_version=> $orig_version,
               version     => $self->format_perl_version($orig_version),
-              is_current  => ($self->current_perl eq $name) && !$self->env("PERLBREW_LIB"),
+              is_current  => ($self->current_perl eq $name) && !($self->current_lib),
               libs => [ $self->local_libs($name) ],
               executable  => $executable
           };
@@ -1850,35 +1866,36 @@ $fatpacked{"App/perlbrew.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'AP
   
       my %env = $self->perlbrew_env($name);
   
-      if ($self->env('SHELL') =~ /(ba|k|z|\/)sh\d?$/) {
-          for my $k (sort keys %env) {
-              my $v = $env{$k};
-              if (defined $v) {
-                  if ($v || ($v && exists($ENV{$k}))) {
-                      $v =~ s/(\\")/\\$1/g;
-                      print "export $k=\"$v\"\n";
-                  }
-              }
-              else {
-                  if (exists $ENV{$k}) {
-                      print "unset $k\n";
-                  }
+      my @statements;
+      for my $k (sort keys %env) {
+          my $v = $env{$k};
+          if (defined($v) && $v ne '') {
+              $v =~ s/(\\")/\\$1/g;
+              push @statements, ["set", $k, $v];
+          } else {
+              if (exists $ENV{$k}) {
+                  push @statements, ["unset", $k];
               }
           }
       }
-      else {
-          for my $k (sort keys %env) {
-              my $v = $env{$k};
-              if (defined $v) {
-                  if ($v || ($v && exists($ENV{$k}))) {
-                      $v =~ s/(\\")/\\$1/g;
-                      print "setenv $k \"$v\"\n";
-                  }
+  
+      if ($self->env('SHELL') =~ /(ba|k|z|\/)sh\d?$/) {
+          for (@statements) {
+              my ($o,$k,$v) = @$_;
+              if ($o eq 'unset') {
+                  print "unset $k\n";
+              } else {
+                  $v =~ s/(\\")/\\$1/g;
+                  print "export $k=\"$v\"\n";
               }
-              else {
-                  if (exists $ENV{$k}) {
-                      print "unsetenv $k\n";
-                  }
+          }
+      } else {
+          for (@statements) {
+              my ($o,$k,$v) = @$_;
+              if ($o eq 'unset') {
+                  print "unsetenv $k\n";
+              } else {
+                  print "setenv $k \"$v\"\n";
               }
           }
       }
@@ -2209,7 +2226,7 @@ $fatpacked{"App/perlbrew.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'AP
   
       my $fullname = $perl_name . '@' . $lib_name;
   
-      my $current  = $self->current_perl . '@' . ($self->env("PERLBREW_LIB") || "");
+      my $current  = $self->current_perl . '@' . $self->current_lib;
   
       my $dir = joinpath($PERLBREW_HOME,  "libs", $fullname);
   
@@ -2233,18 +2250,13 @@ $fatpacked{"App/perlbrew.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'AP
   
   sub run_command_lib_list {
       my ($self) = @_;
-  
-      my $current = "";
-      if ($self->current_perl && $self->env("PERLBREW_LIB")) {
-          $current = $self->current_perl . "@" . $self->env("PERLBREW_LIB");
-      }
-  
       my $dir = joinpath($PERLBREW_HOME,  "libs");
       return unless -d $dir;
   
       opendir my $dh, $dir or die "open $dir failed: $!";
       my @libs = grep { !/^\./ && /\@/ } readdir($dh);
   
+      my $current = $self->current_env;
       for (@libs) {
           print $current eq $_ ? "* " : "  ";
           print "$_\n";
@@ -2417,7 +2429,8 @@ $fatpacked{"App/perlbrew.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'AP
   }
   
   sub BASHRC_CONTENT() {
-      return "export PERLBREW_BASHRC_VERSION=$VERSION\n\n" . sprintf <<'RC', $PERLBREW_ROOT;
+      return "export PERLBREW_BASHRC_VERSION=$VERSION\n" .
+             (exists $ENV{PERLBREW_ROOT} ? "export PERLBREW_ROOT=$PERLBREW_ROOT\n" : "") . "\n" . <<'RC';
   
   __perlbrew_reinit() {
       if [[ ! -d "$PERLBREW_HOME" ]]; then
@@ -2430,45 +2443,45 @@ $fatpacked{"App/perlbrew.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'AP
       __perlbrew_set_path
   }
   
+  __perlbrew_purify () {
+      local path patharray outsep
+      if [[ -n "$BASH_VERSION" ]]; then
+          IFS=: read -ra patharray <<< "$1"
+      fi
+      if [[ -n "$ZSH_VERSION" ]]; then
+          IFS=: read -rA patharray <<< "$1"
+      fi
+      for path in ${patharray[@]} ; do
+          case "$path" in
+              (*"$PERLBREW_HOME"*) ;;
+              (*"$PERLBREW_ROOT"*) ;;
+              (*) printf '%s' "$outsep$path" ; outsep=: ;;
+          esac
+      done
+  }
+  
   __perlbrew_set_path () {
-      MANPATH_WITHOUT_PERLBREW=`perl -e 'print join ":", grep { index($_, $ENV{PERLBREW_HOME}) < 0 } grep { index($_, $ENV{PERLBREW_ROOT}) < 0 } split/:/,qx(manpath 2> /dev/null);'`
-      if [ -n "$PERLBREW_MANPATH" ]; then
-          export MANPATH="$PERLBREW_MANPATH:$MANPATH_WITHOUT_PERLBREW"
-      else
-          export MANPATH="$MANPATH_WITHOUT_PERLBREW"
-      fi
-      unset MANPATH_WITHOUT_PERLBREW
-  
-      PATH_WITHOUT_PERLBREW=$(eval $perlbrew_command display-pristine-path)
-      if [ -n "$PERLBREW_PATH" ]; then
-          export PATH=${PERLBREW_PATH}:${PATH_WITHOUT_PERLBREW}
-      else
-          export PATH=${PERLBREW_ROOT}/bin:${PATH_WITHOUT_PERLBREW}
-      fi
-      unset PATH_WITHOUT_PERLBREW
-  
+      export MANPATH=$PERLBREW_MANPATH${PERLBREW_MANPATH:+:}$(__perlbrew_purify "$(manpath)")
+      export PATH=${PERLBREW_PATH:-$PERLBREW_ROOT/bin}:$(__perlbrew_purify $PATH)
       hash -r
   }
   
   __perlbrew_set_env() {
-      local code="$($perlbrew_command env $@)"
-      local exit_status="$?"
-      if [[ $exit_status -eq 0 ]] ; then
-          eval "$code"
-      else
-          return $exit_status
-      fi
+      local code
+      code="$($perlbrew_command env $@)" || return $?
+      eval "$code"
   }
   
   __perlbrew_activate() {
-      [[ -n $(alias perl 2>/dev/null) ]] && unalias perl 2>/dev/null
+      if [[ -n "$BASH_VERSION" ]]; then
+          [[ $(type -t perl) == alias ]] && unalias perl 2> /dev/null
+      fi
+      if [[ -n "$ZSH_VERSION" ]]; then
+          [[ -n $(alias perl 2>/dev/null) ]] && unalias perl 2>/dev/null
+      fi
   
       if [[ -n "$PERLBREW_PERL" ]]; then
-          if [[ -z "$PERLBREW_LIB" ]]; then
-              __perlbrew_set_env $PERLBREW_PERL
-          else
-              __perlbrew_set_env $PERLBREW_PERL@$PERLBREW_LIB
-          fi
+          __perlbrew_set_env "$PERLBREW_PERL${PERLBREW_LIB:+@}$PERLBREW_LIB"
       fi
   
       __perlbrew_set_path
@@ -2543,7 +2556,7 @@ $fatpacked{"App/perlbrew.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'AP
       return ${exit_status:-0}
   }
   
-  [[ -z "$PERLBREW_ROOT" ]] && export PERLBREW_ROOT="%s"
+  [[ -z "$PERLBREW_ROOT" ]] && export PERLBREW_ROOT="$HOME/perl5/perlbrew"
   [[ -z "$PERLBREW_HOME" ]] && export PERLBREW_HOME="$HOME/.perlbrew"
   
   if [[ ! -n "$PERLBREW_SKIP_INIT" ]]; then
@@ -2596,10 +2609,11 @@ $fatpacked{"App/perlbrew.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'AP
   end
   
   function __perlbrew_set_path
-      set -l MANPATH_WITHOUT_PERLBREW (perl -e 'print join " ", grep { index($_, $ENV{PERLBREW_HOME}) < 0 } grep { index($_, $ENV{PERLBREW_ROOT}) < 0 } split/:/,qx(manpath 2> /dev/null);')
+      set -l MANPATH_WITHOUT_PERLBREW (perl -e 'print join ":", grep { index($_, $ENV{PERLBREW_HOME}) < 0 } grep { index($_, $ENV{PERLBREW_ROOT}) < 0 } split/:/,qx(manpath 2> /dev/null);')
   
       if test -n "$PERLBREW_MANPATH"
-          set -x MANPATH $PERLBREW_MANPATH $MANPATH_WITHOUT_PERLBREW
+          set -l PERLBREW_MANPATH $PERLBREW_MANPATH":"
+          set -x MANPATH {$PERLBREW_MANPATH}{$MANPATH_WITHOUT_PERLBREW}
       else
           set -x MANPATH $MANPATH_WITHOUT_PERLBREW
       end
@@ -6119,7 +6133,7 @@ Without a parameter, shows the version of perl currently selected.
 
 Usage: perlbrew list
 
-List all perl installations inside perlbrew root specifed by C<$PERLBREW_ROOT>
+List all perl installations inside perlbrew root specified by C<$PERLBREW_ROOT>
 environment variable. By default, the value is C<~/perl5/perlbrew>.
 
 If there are libs associated to some perl installations, they will be included
